.Dd $Mdocdate: January 24 2021 $
.Dt PICO-WAYFIRE-SETUP 1
.Os
.Sh NAME
.Nm pico-wayfire-setup
.Nd dotfiles for creating a consistent look on wayfire
.Sh SYNOPSIS
.Oo PICO_WAYFIRE_TARGETS Ns = Ns Do Ar targets Dc Oc Nm
.Op Ar help
.Sh DESCRIPTION
.Nm
is a script to setup dotfiles to create a consistent look on
.Sy wayfire
and other companion software for wayland.
.Pp
.Nm
uses the
.Ev PICO_WAYFIRE_TARGETS
environment variable as an indicator for softwares for
which to setup the dotfiles.
.Pp
For example, to only setup dotfiles for
.Sy wayfire , mako
and
.Sy waybar :
.Bd -literal -offset width
$ PICO_WAYFIRE_TARGETS="wayfire mako waybar" pico-wayfire-setup
.Ed
.Pp
If
.Ev PICO_WAYFIRE_TARGETS
is unset, all
.Ar targets
are installed.
.Pp
To view available
.Ar targets ,
run:
.Bd -literal -offset width
$ pico-wayfire-setup help
.Ed
.Sh AUTHORS
.Nm
is written by
.An Aisha Tammy Aq Mt floss@bsd.ac
and maintained at
.Lk https://github.com/bsd-ac/pico-wayfire .
