.Dd $Mdocdate: January 24 2021 $
.Dt PICO-WAYFIRE 1
.Os
.Sh NAME
.Nm pico-wayfire ,
.Nm pico-wayfire-setup
.Nd dotfiles for creating a consistent look on wayfire
.Sh SYNOPSIS
.Nm
.Op Ar help
.Sh DESCRIPTION
.Nm
is a script to setup dotfiles for various software to
create a consistent look on
.Sy wayfire
and other companion software for wayland.
.Pp
.Nm
uses the
.Ev PICO_WAYFIRE_SETUP
environment variable as an indicator for softwares for
which to setup the dotfiles.
.Pp
For example, to only setup dotfiles for
.Sy wayfire , mako
and
.Sy waybar :
.Bd -literal
    $ env -i PICO_WAYFIRE_SETUP="wayfire mako waybar" \
        pico-wayfire-setup
.Ed
.Pp
If
.Ev PICO_WAYFIRE_SETUP
is unset, all
.Ar targets
are installed.
.Pp
To view available
.Ar targets ,
run:
.Bd -literal
    $ pico-wayfire-setup help
.Ed
.Sh AUTHORS
.Nm
is written by
.An Aisha Tammy Aq Mt floss@bsd.ac .
